#!/usr/bin/env python3
"""Abstractive summarization script preserving named entities.

This script reads a text file containing a news article and outputs an
abstractive summary generated by a transformer-based model from the
Hugging Face Transformers library. It uses spaCy to extract named
entities from the original article and checks that the generated summary
includes these entities. Entities missing from the summary are appended
at the end to encourage preservation of key information and
relationships.

Example usage:
    python summarizer.py article.txt

Requirements:
    transformers
    spacy
    en_core_web_sm (spaCy model)

Note: Running this script requires downloading model weights. In a
restricted environment without network access, download the required
models beforehand.
"""

import argparse
from pathlib import Path
from typing import Set

import spacy
from transformers import pipeline


def load_article(path: Path) -> str:
    """Read the article from a file."""
    with path.open(encoding="utf-8") as f:
        return f.read()


def extract_entities(text: str, nlp) -> Set[str]:
    """Return the set of named entities in the text."""
    doc = nlp(text)
    return {ent.text for ent in doc.ents}


def generate_summary(text: str, model_name: str) -> str:
    """Generate a summary using a transformer-based summarization pipeline."""
    summarizer = pipeline("summarization", model=model_name)
    result = summarizer(text, max_length=200, min_length=60, truncation=True)
    return result[0]["summary_text"]


def ensure_entities(summary: str, entities: Set[str]) -> str:
    """Append missing named entities to the summary."""
    missing = [ent for ent in entities if ent not in summary]
    if missing:
        summary += "\n\nMissing entities: " + ", ".join(missing)
    return summary


def main() -> None:
    parser = argparse.ArgumentParser(description="Summarize news articles")
    parser.add_argument("article", type=Path, help="Path to the article text file")
    parser.add_argument(
        "--model",
        default="facebook/bart-large-cnn",
        help="Hugging Face model for summarization",
    )
    args = parser.parse_args()

    text = load_article(args.article)

    nlp = spacy.load("en_core_web_sm")
    entities = extract_entities(text, nlp)

    summary = generate_summary(text, args.model)
    summary = ensure_entities(summary, entities)

    print(summary)


if __name__ == "__main__":
    main()
